name: tflint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - '**.tf'
      - '**.tfvars'
      #- '!examples/**'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup TFLint
        # You may pin to the exact commit or the version.
        # uses: terraform-linters/setup-tflint@7cf6558386ea02736c0a5edd3031f39c2dfeb206
        uses: terraform-linters/setup-tflint@v1.1.0
        
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact
        
      - name: Render terraform docs and push changes back to PR - module
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "docs: terraform-docs: automated action - module"

      - name: Render terraform docs and push changes back to PR - examples/standard
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: examples/standard
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "docs: terraform-docs: automated action - examples/standard"
      
      - name: Render terraform docs and push changes back to PR - examples/custom
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: examples/custom
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "docs: terraform-docs: automated action - examples/custom"
        
